---
# tasks file for aiops
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Ansible Install Playbook V0.1
#
#  CloudPak for MultiCloud Management
#
#  Â©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

- name: TIMESTAMP -              ðŸŸ¢ START - STORAGE CLASS
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Get Config File
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: LOAD PARAMETERS -        ðŸ‘“ Load parameters
  include_vars: ../00_config_cp4waiops.yaml


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Determine Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: STORAGECLASS -           ðŸŒ Get Cluster FQDN
  shell: |
    CLUSTER_ROUTE=$(oc get routes console -n openshift-console | tail -n 1 2>&1 ) 
    CLUSTER_FQDN=$( echo $CLUSTER_ROUTE | awk '{print $2}')
    echo ${CLUSTER_FQDN##*console.}
  register: CLUSTER_NAME

- name: PLATFORM -               ðŸŒ Check Cluster Connectivity
  fail: msg="You must be logged in to the server!"
  when: CLUSTER_NAME.stdout==""

# --------------------------------------------------------------------------------------------------------------------------------------
# If Storage Classes are overridden
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -           â˜‘ï¸  Determine Storage Class File Override
  set_fact: WAIOPS_STORAGE_CLASS_LARGE_BLOCK={{ STORAGECLASS_BLOCK_OVERRIDE }}
  when: STORAGECLASS_BLOCK_OVERRIDE!="not_configured"


- name: STORAGECLASS -           â˜‘ï¸  Determine Storage Class Block Override
  set_fact: WAIOPS_STORAGE_CLASS_FILE={{ STORAGECLASS_FILE_OVERRIDE }}
  when: STORAGECLASS_FILE_OVERRIDE!="not_configured"


# --------------------------------------------------------------------------------------------------------------------------------------
# Otherwise determine Storage Class
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -           â˜‘ï¸  Determine File Storage Class
  shell: |
      CLUSTER_NAME={{ CLUSTER_NAME.stdout_lines[0] }}
      if [ -z "${CLUSTER_NAME##*fyre.ibm.com*}" ];
      then
          echo "rook-cephfs"
      else
        if [ -z "${CLUSTER_NAME##*appdomain.cloud*}" ]; 
        then
            echo "ibmc-file-gold-gid"
        else
          # Use Default Class (storageclass.kubernetes.io/is-default-class:true)
          SC_DEFAULT_STRING=$(oc get sc | grep "(default)")
          if [ -z "${SC_DEFAULT_STRING##*(default)*}" ];
          then
            echo ${SC_DEFAULT_STRING//\(*} 
          else
            echo "No default StorageClass defined. Unable to determine what SC to use." 
            echo "Please define one using storageclass.kubernetes.io/is-default-class:true"
            echo "or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
            exit 1
          fi
        fi
      fi
  register: INSTALL_DETECTED_STORAGECLASS
  when: STORAGECLASS_FILE_OVERRIDE=="not_configured"
  #args:
  #  executable: /bin/bash



# --------------------------------------------------------------------------------------------------------------------------------------
# Otherwise determine Storage Class
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -           â˜‘ï¸  Determine Block Storage Class
  shell: |
      CLUSTER_NAME={{ CLUSTER_NAME.stdout_lines[0] }}
      if [ -z "${CLUSTER_NAME##*fyre.ibm.com*}" ]; 
      then
          echo "rook-ceph-block"
      else
        if [ -z "${CLUSTER_NAME##*appdomain.cloud*}" ]; 
        then
            echo "ibmc-block-gold"
        else
          # Use Default Class (storageclass.kubernetes.io/is-default-class:true)
          SC_DEFAULT_STRING=$(oc get sc | grep "(default)")
          if [ -z "${SC_DEFAULT_STRING##*(default)*}" ]; 
          then
            echo ${SC_DEFAULT_STRING//\(*} 
          else
            echo "No default StorageClass defined. Unable to determine what SC to use." 
            echo "Please define one using storageclass.kubernetes.io/is-default-class:true"
            echo "or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
            exit 1
          fi
        fi
      fi
  register: INSTALL_DETECTED_BLOCK_STORAGECLASS
  when: STORAGECLASS_BLOCK_OVERRIDE=="not_configured"
  #args:
  #  executable: /bin/bash


# --------------------------------------------------------------------------------------------------------------------------------------
# Set File Storage Class
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -           ðŸ’¾ Set WAIOPS_STORAGE_CLASS_FILE={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }}
  set_fact: WAIOPS_STORAGE_CLASS_FILE={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }} 
  when: STORAGECLASS_FILE_OVERRIDE=="not_configured"

# --------------------------------------------------------------------------------------------------------------------------------------
# Set Large Block Storage Class to same value
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -           ðŸ’¾ Set WAIOPS_STORAGE_CLASS_LARGE_BLOCK={{ INSTALL_DETECTED_BLOCK_STORAGECLASS.stdout_lines[0] }} 
  set_fact: WAIOPS_STORAGE_CLASS_LARGE_BLOCK={{ INSTALL_DETECTED_BLOCK_STORAGECLASS.stdout_lines[0] }} 
  when: STORAGECLASS_BLOCK_OVERRIDE=="not_configured" 



# --------------------------------------------------------------------------------------------------------------------------------------
# Check File Storage Class exists
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -           â˜‘ï¸  Check File Storage Class exists {{ WAIOPS_STORAGE_CLASS_FILE }}
  shell: |
          SC_EXISTS=$(oc get sc {{ WAIOPS_STORAGE_CLASS_FILE }} --ignore-not-found --no-headers| wc -l|tr -d ' ')
          if [ $SC_EXISTS -gt 0 ];
          then
            echo "OK"
          else
            echo "Storage Class does not exist!"
            echo "Please revioew your block storage class or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
            exit 1
          fi     
  register: INSTALL_DETECTED_BLOCK_STORAGECLASS
  args:
    executable: /bin/bash


# --------------------------------------------------------------------------------------------------------------------------------------
# Check Large Block Storage Class exists
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -           â˜‘ï¸  Check Large Block Storage Class exists {{ WAIOPS_STORAGE_CLASS_LARGE_BLOCK }}
  shell: |
          SC_EXISTS=$(oc get sc {{ WAIOPS_STORAGE_CLASS_LARGE_BLOCK }} --ignore-not-found --no-headers| wc -l|tr -d ' ')
          if [ $SC_EXISTS -gt 0 ];
          then
            echo "OK"
          else
            echo "Storage Class does not exist!"
            echo "Please revioew your block storage class or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
            exit 1
          fi     
  register: INSTALL_DETECTED_BLOCK_STORAGECLASS
  args:
    executable: /bin/bash


- name: STORAGECLASS -           ðŸ’¿ Storage Class 
  debug: 
    msg: 
    - "** Global Storage Classes for CP4WAIOPS installation *************************************************************************"
    - " CP4WAIOPS Storage Class File:          {{WAIOPS_STORAGE_CLASS_FILE}}"
    - " CP4WAIOPS Storage Class Large Block:   {{WAIOPS_STORAGE_CLASS_LARGE_BLOCK}}"

- name: LOGGING -                ðŸ“¥ WRITE TO LOGFILE
  shell: |
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - ""Global Storage Classes for CP4WAIOPS installation:"  >> ../installAIManager.log
    echo $currentDate" - "$USER" - "" CP4WAIOPS Storage Class File:          {{WAIOPS_STORAGE_CLASS_FILE}}"  >> ../installAIManager.log
    echo $currentDate" - "$USER" - "" CP4WAIOPS Storage Class Large Block:   {{WAIOPS_STORAGE_CLASS_LARGE_BLOCK}}"  >> ../installAIManager.log

  ignore_errors: yes
