---

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Generic Event Webhook 
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: TIMESTAMP -              ðŸŸ¢ START - AIOPS TOOLBOX
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"



- name: LOAD PARAMETERS -        ðŸ‘“ Load parameters
  include_vars: ../00_config_cp4waiops.yaml




- name: TOOLBOX -                ðŸš€ DEPLOY TOOLBOX POD
  kubernetes.core.k8s:
    state: present
    template: ./templates/waiops-toolbox/create-waiops-toolbox.yaml
