

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Open Doc
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: AI MANAGER -             ðŸŒ Get AI MANAGER LOGINS
  shell: |
    export WAIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    export AIMANAGER_ROUTE=$(oc get route -n $WAIOPS_NAMESPACE cpd -o jsonpath={.spec.host})
    echo "                ðŸŒ URL:      https://$AIMANAGER_ROUTE"
    echo ""
    echo "                ðŸ§‘ User:     $(oc -n ibm-common-services get secret platform-auth-idp-credentials -o jsonpath='{.data.admin_username}' | base64 --decode && echo)"
    echo "                ðŸ” Password: $(oc -n ibm-common-services get secret platform-auth-idp-credentials -o jsonpath='{.data.admin_password}' | base64 --decode)"

    export URL=https://$AIMANAGER_ROUTE
    if [ -x "$(command -v open)" ]; then
      open $URL
    else 
      if [ -x "$(command -v firefox)" ]; then
        firefox $URL
      else 
        if [ -x "$(command -v google-chrome)" ]; then
          google-chrome $URL
        fi
      fi
    fi
  ignore_errors: yes
  register: LOGINS


- name: AI MANAGER -             ðŸŸ¢ AI MANAGER LOGINS
  debug: 
    var: LOGINS.stdout_lines


- name: LOGGING -                ðŸ“¥ WRITE TO LOGFILE
  shell: |
    export MESSAGE=" ðŸ•¦ Wait for AI Manager to become ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo "              ðŸ“¥ AI Manager Login:"  >> ../installAIManager.log
    echo "" >> ../installAIManager.log
    echo "                ðŸŒ URL:      https://$(oc get route -n {{WAIOPS_NAMESPACE}} cpd -o jsonpath={.spec.host})"  >> ../installAIManager.log
    echo "" >> ../installAIManager.log
    echo "                ðŸ§‘ User:     $(oc -n ibm-common-services get secret platform-auth-idp-credentials -o jsonpath='{.data.admin_username}' | base64 --decode && echo)" >> ../installAIManager.log
    echo "                ðŸ” Password: $(oc -n ibm-common-services get secret platform-auth-idp-credentials -o jsonpath='{.data.admin_password}' | base64 --decode)" >> ../installAIManager.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log

  ignore_errors: yes
