
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX (open source Ansible Tower)
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX
# --------------------------------------------------------------------------------------------------------------------------------------
# Create AWX

- name: TIMESTAMP -              ðŸŸ¢ START - INSTALL AWX
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: AWX -                    ðŸ“¥ WRITE TO LOGFILE
  shell: |
    export MESSAGE="Installing AWX"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes

  
- name: AWX -                    ðŸš€ Create AWX Operator
  kubernetes.core.k8s:
    state: present
    namespace: awx
    src: ./templates/awx/operator-install.yaml
  
- name: AWX -                    ðŸš€ Create AWX Instance (while waiting for CP4WAIOPS Installation to progress)
  kubernetes.core.k8s:
    state: present
    namespace: awx
    src: ./templates/awx/awx-deploy-cr.yml


