- name: TIMESTAMP -              üü¢ START - RUN METRIC TRAINING
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"




- name: LOGGING -              üü¢ WRITE TO LOGFILE
  shell: |
    export MESSAGE="Run MEtrics Training"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes



- name: TRAINING RUN METRIC -       üöÄ RUN METRIC TRAINING
  shell: |
    set -x
    
    echo "  ***************************************************************************************************************************************************"
    echo "   üõ†Ô∏è  Run Analysis: MEtricAnomaly"
    export FILE_NAME=run-analysis-METRIC.graphql
    ../tools/02_training/scripts/execute-graphql.sh


  register: output_string
  ignore_errors: yes
- name: TRAINING RUN METRIC -       ‚úÖ RESULT
  debug: 
    var: output_string.stdout_lines
  #when: PRINT_LOGINS == true

