

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Open Doc
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: LOGGING -              ğŸŸ¢ WRITE TO LOGFILE
  shell: |
    export MESSAGE=" ğŸŒ Open doc at https://github.ibm.com/NIKH/aiops-install-ansible-fvt-33#3-ai-manager-configuration"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes



- name: DOCUMENTATION -          ğŸŒ Open Documentation
  shell: |
    open https://github.ibm.com/NIKH/aiops-install-ansible-fvt-33#3-ai-manager-configuration
  ignore_errors: yes



