
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX (open source Ansible Tower)
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX
# --------------------------------------------------------------------------------------------------------------------------------------
# Create AWX

- name: TIMESTAMP -              游릭 START - INSTALL AWX
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: LOGGING -              游릭 WRITE TO LOGFILE
  shell: |
    export MESSAGE="Installing AWX"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes

  
- name: AWX -                游 Create AWX Operator
  kubernetes.core.k8s:
    state: present
    namespace: awx
    src: ./templates/awx/operator-install.yaml
  
- name: AWX -                游 Create AWX Instance (while waiting for CP4WAIOPS Installation to progress)
  kubernetes.core.k8s:
    state: present
    namespace: awx
    src: ./templates/awx/awx-deploy-cr.yml


- name: LOGGING -              游릭 WRITE TO LOGFILE
  shell: |
    export MESSAGE="Installing AWX"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "              游닌 AWX Login:"  >> ../installAIManager.log
    echo ""  >> ../installAIManager.log
    echo "                游깶 URL:      https://$(oc get route -n awx awx -o jsonpath={.spec.host})"  >> ../installAIManager.log
    echo "                游븸 User:     admin"  >> ../installAIManager.log
    echo "                游댏 Password: $(oc -n awx get secret awx-admin-password -o jsonpath='{.data.password}' | base64 --decode && echo)"  >> ../installAIManager.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
  ignore_errors: yes


