

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Open Doc
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: LOAD PARAMETERS -        üëì Load parameters
  include_vars: ../00_config_cp4waiops.yaml


- name: DOCUMENTATION -          üì• WRITE TO LOGFILE
  shell: |
    export MESSAGE=" üåè Open doc at {{URL_STEP_3}}"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes


- name: DOCUMENTATION -          üåè Open Documentation
  shell: |
    export URL={{URL_STEP_3}}
    if [ -x "$(command -v open)" ]; then
      open $URL
    else 
      if [ -x "$(command -v firefox)" ]; then
        firefox $URL
      else 
        if [ -x "$(command -v google-chrome)" ]; then
          google-chrome $URL
        fi
      fi
    fi
  ignore_errors: yes



