
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install Demo Apps
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Install RobotShop
# --------------------------------------------------------------------------------------------------------------------------------------
- name: TIMESTAMP -              ðŸŸ¢ START - INSTALL DEMO APPS
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: DEMO APPS -              ðŸ“¥ WRITE TO LOGFILE
  shell: |
    export MESSAGE="Installing Demo Apps"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes


- name: DEMO APPS -              ðŸ”Ž Check RobotShop
  shell: |
    oc get namespace --ignore-not-found robot-shop
  ignore_errors: yes
  register: OBJECT_EXISTS




- name: DEMO APPS -              ðŸš€ Install RobotShop
  block:
  - name: DEMO APPS -              ðŸš€ Create robot-shop namespace
    kubernetes.core.k8s:
      api_version: v1
      kind: Namespace
      name: "robot-shop"
      state: present
    #when: INSTALL_DEMO_APPS == true

  - name: DEMO APPS -              ðŸš€ Create robot-shop service account
    shell: |
      oc adm policy add-scc-to-user privileged -n robot-shop -z robot-shop
      oc create clusterrolebinding default-robotinfo1-admin --clusterrole=cluster-admin --serviceaccount=robot-shop:robot-shop
      oc adm policy add-scc-to-user privileged -n robot-shop -z default                                
      oc create clusterrolebinding default-robotinfo2-admin --clusterrole=cluster-admin --serviceaccount=robot-shop:default
    ignore_errors: yes
    register: demo_robot_shop
    #when: INSTALL_DEMO_APPS == true
              

  - name: DEMO APPS -              ðŸš€ Create robot-shop application
    kubernetes.core.k8s:
      state: present
      namespace: robot-shop
      src: ./templates/demo_apps/robotshop/robot-all-in-one.yaml
    #when: INSTALL_DEMO_APPS == true

  - name: DEMO APPS -              ðŸš€ Create robot-shop load generation
    kubernetes.core.k8s:
      state: present
      namespace: robot-shop
      src: ./templates/demo_apps/robotshop/load-deployment.yaml
    #when: INSTALL_DEMO_APPS == true
  when: OBJECT_EXISTS.stdout|length == 0





