
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Waiting for CP4WAIOPS installation to finish
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    
- name: LOGGING -                ðŸ“¥ WRITE TO LOGFILE
  shell: |
    export MESSAGE=" ðŸ•¦ Wait for AWX to become ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes


# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for awx Namespace to be ready
# --------------------------------------------------------------------------------------------------------------------------------------

- name: CHECK -                  ðŸ•¦ Wait for pods in namespace awx ready
  shell: |
    NUM_PODS=$(oc get pods -n awx| grep postgres|grep 1/1 | wc -l| tr -d ' ')
    echo $NUM_PODS
  register: kubectl_num_pods
  until: kubectl_num_pods.stdout|int == 1
  retries: 50
  delay: 15



- name: CHECK -                  ðŸ•¦ Wait for awx UI to become ready
  shell: |
    export AWX_ROUTE=$(oc get route -n awx awx -o jsonpath={.spec.host})
    export AWX_URL=$(echo "https://$AWX_ROUTE")

    READY=$(curl -s $AWX_URL|grep "Application is not available")
    echo $READY
  register: ready
  until:  ("Application is not available" not in ready.stdout)
  retries: 50
  delay: 15



- name: LOGGING -                ðŸ“¥ WRITE TO LOGFILE
  shell: |
    export MESSAGE=" âœ… AWX is ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes


- name: AWX -                    ðŸ“¥ WRITE TO LOGFILE
  shell: |
    export MESSAGE="Installing AWX"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "              ðŸ“¥ AWX Login:"  >> ../installAIManager.log
    echo ""  >> ../installAIManager.log
    echo "                ðŸŒ URL:      https://$(oc get route -n awx awx -o jsonpath={.spec.host})"  >> ../installAIManager.log
    echo "                ðŸ§‘ User:     admin"  >> ../installAIManager.log
    echo "                ðŸ” Password: $(oc -n awx get secret awx-admin-password -o jsonpath='{.data.password}' | base64 --decode && echo)"  >> ../installAIManager.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
  ignore_errors: yes



- name: AWX -                    ðŸ“¥ Adapt service account
  shell: |
    oc create clusterrolebinding awx-default --clusterrole=cluster-admin --serviceaccount=awx:default
  ignore_errors: yes


