

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Zen in Common Services being ready
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************



- name: LOGGING -              ðŸŸ¢ WRITE TO LOGFILE
  shell: |
    export MESSAGE=" ðŸš€ Starting Ai Manager Base Install (01_AIManager-install)"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "**********************************************************************************************************************************************************" >> ../installAIManager.log
    echo "**********************************************************************************************************************************************************" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes


