#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.3
#
#  CloudPak for Watson AIOps
#
#  Â©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - IBM Operator
#  - AI Manager
#  - OpenLDAP & Register with AI Manager
#  - AWX (Open Source Ansible Tower) with preloaded Playbooks
#  - RobotShop Demo App
#  - Demo Service Account 
#  - External Routes (Flink, Topology, ...)
#  - Disables ASM Service match rule 
#  - Creates valid certificate for Ingress (Slack) 
#  - Train Models
#    - Create Training Definitions (TG, LAD, CR, SI. Turn off RSA) 
#    - Create Training Data (LAD, SNOW) 
#    - Train Models (TG, LAD, CR, SI) 
#  
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles:  
# Placeholder for customization
    - role: 00_pre

# Run Prerequisites
    - role: 01_initialization
  
    - role: 02_rook-ceph
      when: (ROOK_CEPH_INSTALL_MODE=="enable" or ROOK_CEPH_INSTALL_MODE=="automatic") and  INSTALL_ROOK_CEPH=="true"

    - role: 03_aiops-get-storage-class
      

    - role: 04_aiops-prerequisites
      

# Install CP4WAIOPS Operator
    - role: 10_aiops-operator
      
      
# Install CP4WAIOPS Instance
    - role: 11_aiops-install
      


# Install Add-Ons while CP4WAIOPS is coming up
    - role: 25_aiops-addons-ldap

    - role: 26_aiops-addons-user

    - role: 27_aiops-addons-demoapps

    #- role: 28_aiops-addons-runbook-bastion
      
    - role: 23_aiops-addons-awx      

    - role: 99_aiops-wait-awx

    - role: 47_aiops-load-awx-runbooks
    

# Wait for Common Services being completely installed
    - role: 99_aiops-wait-common-services
      

    - role: 99_aiops-wait-for-zen
      

    - role: 30_aiops-create-routes



# Wait for CP4WAIOPS being completely installed
    - role: 99_aiops-wait-cp4waiops
      

    - role: 31_aiops-patch-ingress
      
    - role: 32_aiops-disable-match-token-rule


# Post installation tasks
    - role: 40_aiops-post-ldap-register


    - role: 48_aiops-load-aimanager-runbooks


# Open documentation
    - role: 99_aiops-open-doc

# Get all login credentials
    - role: 90_aiops-logins
      when: PRINT_LOGINS


# Create Training definitions, load data and train models
    - role: 85_training-check-exists
    - role: 86_training-create-tg
      when: TRAINING_EXISTS==false
    - role: 86_training-create-snow
      when: TRAINING_EXISTS==false
    - role: 86_training-create-logs
      when: TRAINING_EXISTS==false
    - role: 87_training-load-snow
      when: TRAINING_EXISTS==false
    - role: 87_training-load-logs
      when: TRAINING_EXISTS==false
    - role: 87_training-load-wait
      when: TRAINING_EXISTS==false
    - role: 88_training-run-snow
      when: TRAINING_EXISTS==false
    - role: 88_training-run-logs
      when: TRAINING_EXISTS==false






