#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing Turbonomic for CP4WAIOPS v3.3
#
#
#  Â©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Create definition Temporal Grouping 
#  - Create definition Similar Incidents
#  - Create definition Change Risk
#  - Create definition Log Anomaly Detection
#  - Load SNOW data into ElasticSearch for training
#  - Load LOG data into ElasticSearch for training
#  - Wait for load to finish
#  - Run training Similar Incidents
#  - Run training Change Risk
#  - Run training Log Anomaly Detection
#  
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles: 
# Placeholder for customization
    - role: 00_pre


# Run Roles 

    - role: 87_training-load-snow

    - role: 87_training-load-logs

    - role: 87_training-load-metric


    - role: 86_training-create-tg

    - role: 86_training-create-metric

    - role: 86_training-create-snow

    - role: 86_training-create-logs


    - role: 87_training-load-wait

    - role: 88_training-run-snow

    - role: 88_training-run-metric

    - role: 88_training-run-logs

















